[package]
name = "hex_instance"
version = "0.2.0"
edition = "2021"

[dependencies]
hex = { git = "https://github.com/a-underscore/hex", version = "0.3.0", branch = "0.3.0" }
ordered-float = "3.9.1"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
